#!/bin/bash
#
# Copyright (c) 2013 Eugene Zhuk.
# Use of this source code is governed by the MIT license that can be found
# in the LICENSE file.

FIND=$(which find)
PWD=$(which pwd)
BASENAME=$(which basename)
LN=$(which ln)

# Check if an action can be performed.
confirm()
{
    while true; do
        read -p "$1" reply
        case "$reply" in
            Y|y) return 0 ;;
            N|n|"") return 1 ;;
        esac
    done
}

# Symlink configuration files into home directory.
for src in $($FIND "$($PWD)" -name ".*" -depth 2 -maxdepth 2); do
    dst=$HOME/$($BASENAME "$src")
    if [[ -e "$dst" ]]; then
        if ! confirm "'$dst' already exists. Do you want to replace it anyway? [y/N]: "; then
            continue
        fi
    fi

    $LN -sfFn "$src" "$dst"
done
