#!/bin/bash

PWD=$(which pwd)
LN=$(which ln)

for NAME in .*; do
  FILE=$HOME/$NAME
  case $NAME in
    .|..|.git|.gitignore|osx) continue
      ;;
    *) LINK="Y"

       if [ -e "$FILE" ]; then
         while true; do
           read -p "'$FILE' already exists. Do you want to replace it anyway? [y/N]: " REPLY
           if [ -z "$REPLY" ]; then
             REPLY="N"
           fi
           case "$REPLY" in
             Y|y) LINK="Y"; break ;;
             N|n) LINK="N"; break ;;
           esac
         done
       fi

       if [ "$LINK" = "Y" ]; then
         echo "Symlinking '$NAME' into '$FILE'"
         $LN -sfFn "$(PWD)/$NAME" $FILE
       fi
      ;;
  esac
done
