#!/bin/bash
#
# Copyright (c) 2013 Eugene Zhuk.
# Use of this source code is governed by the MIT license that can be found
# in the LICENSE file.

FIND=$(which find)
PWD=$(which pwd)
BASENAME=$(which basename)
LN=$(which ln)

confirm()
{
    while true; do
	read -p "$1" REPLY
	case "$REPLY" in
	    Y|y) return 0 ;;
	    N|n|"") return 1 ;;
	esac
    done
}

for SRC in $($FIND "$($PWD)" -name ".*" -depth 2 -maxdepth 2); do
    DST=$HOME/$($BASENAME "$SRC")
    if [[ -e "$DST" ]]; then
	if ! confirm "'$DST' already exists. Do you want to replace it anyway? [y/N]: "; then
	    continue
	fi
    fi

    $LN -sfFn "$SRC" "$DST"
done
