#!/bin/bash

sudo -v

# Set computer name.
sudo scutil --set ComputerName "MacBook Pro"
sudo scutil --set LocalHostName "MacBook-Pro"
sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string "MACBOOKPRO"

# Check for software updates every day.
defaults write com.apple.SoftwareUpdate ScheduleFrequency -int 1

# Enable tap to click.
defaults write com.apple.AppleMultitouchTrackpad Clicking -int 1
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -int 1

# Increase the key repeat rate.
defaults write NSGlobalDomain KeyRepeat -int 3
# Decrease the delay until repeat.
defaults write NSGlobalDomain InitialKeyRepeat -int 15

# Show battery level percentage.
defaults write com.apple.menuextra.battery ShowPercent -string "YES"

# Minimize windows into application icon.
defaults write com.apple.dock minimize-to-application -int 1

# Show all filename extensions.
defaults write NSGlobalDomain AppleShowAllExtensions -int 1

# Enable quit finder menu item.
defaults write com.apple.finder QuitMenuItem -int 1
# Empty Trash securely by default.
defaults write com.apple.finder EmptyTrashSecurely -int 1

# Do not create .DS_Store files on network volumes.
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true

# Show scrollbar in terminal only when scrolling.
defaults write com.apple.Terminal AppleShowScrollBars -string "WhenScrolling"

# Do not enable rich text format by default.
defaults write com.apple.TextEdit RichText -int 0

# Do not automatically open safe files in Safari after downloading.
defaults write com.apple.Safari AutoOpenSafeDownloads -bool false
