#!/bin/bash

sudo -v

# Set computer name.
sudo scutil --set ComputerName "MacBook Pro"
sudo scutil --set LocalHostName "MacBook-Pro"
sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string "MACBOOKPRO"

# Check for software updates every day.
defaults write com.apple.SoftwareUpdate ScheduleFrequency -int 1

# Require password immediately after sleep or screen saver begins.
defaults write com.apple.screensaver askForPassword -int 1
defaults write com.apple.screensaver askForPasswordDelay -int 0

# Enable tap to click.
defaults write com.apple.AppleMultitouchTrackpad Clicking -int 1
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -int 1

# Increase the key repeat rate.
defaults write NSGlobalDomain KeyRepeat -int 3
# Decrease the delay until repeat.
defaults write NSGlobalDomain InitialKeyRepeat -int 15

# Enable Firewall (specific services, stealth mode, logging).
sudo defaults write /Library/Preferences/com.apple.alf globalstate -int 1
sudo defaults write /Library/Preferences/com.apple.alf stealthenabled -int 1
sudo defaults write /Library/Preferences/com.apple.alf loggingenabled -int 1
# Reload Firewall.
launchctl unload /System/Library/LaunchAgents/com.apple.alf.useragent.plist
sudo launchctl unload /System/Library/LaunchDaemons/com.apple.alf.agent.plist
sudo launchctl load /System/Library/LaunchDaemons/com.apple.alf.agent.plist
launchctl load /System/Library/LaunchAgents/com.apple.alf.useragent.plist

# Turn Bluetooth off.
sudo defaults write /Library/Preferences/com.apple.Bluetooth ControllerPowerState -int 0
sudo launchctl unload /System/Library/LaunchDaemons/com.apple.blued.plist
sudo launchctl load /System/Library/LaunchDaemons/com.apple.blued.plist

# Disable IR remote control.
sudo defaults write /Library/Preferences/com.apple.driver.AppleIRController DeviceEnabled -int 0

# Hide Bluetooth and Time Machine icons.
defaults write com.apple.systemuiserver menuExtras -array \
    "/System/Library/CoreServices/Menu Extras/Displays.menu" \
    "/System/Library/CoreServices/Menu Extras/AirPort.menu" \
    "/System/Library/CoreServices/Menu Extras/Volume.menu" \
    "/System/Library/CoreServices/Menu Extras/Battery.menu" \
    "/System/Library/CoreServices/Menu Extras/Clock.menu"

# Show battery level percentage.
defaults write com.apple.menuextra.battery ShowPercent -string "YES"

# Minimize windows into application icon.
defaults write com.apple.dock minimize-to-application -int 1

# Show all filename extensions.
defaults write NSGlobalDomain AppleShowAllExtensions -int 1

# Enable quit finder menu item.
defaults write com.apple.finder QuitMenuItem -int 1
# Enable list view by default.
defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv"
# Empty Trash securely by default.
defaults write com.apple.finder EmptyTrashSecurely -int 1

# Do not create .DS_Store files on network volumes.
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true

# Show scrollbar in terminal only when scrolling.
defaults write com.apple.Terminal AppleShowScrollBars -string "WhenScrolling"

# Do not enable rich text format by default.
defaults write com.apple.TextEdit RichText -int 0

# Do not automatically open safe files in Safari after downloading.
defaults write com.apple.Safari AutoOpenSafeDownloads -int 0
# Do not show Sidebar in Top Sites.
defaults write com.apple.Safari ShowSidebarInTopSites -int 0
